2025-07-06 08:49:17,927:DEBUG:certbot._internal.main:certbot version: 2.11.0
2025-07-06 08:49:17,927:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2025-07-06 08:49:17,927:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'apptronium@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'apptronium.com', '-d', 'www.apptronium.com', '--logs-dir', '/var/log/letsencrypt']
2025-07-06 08:49:17,927:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-07-06 08:49:17,939:DEBUG:certbot._internal.log:Root logging level set at 30
2025-07-06 08:49:17,941:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2025-07-06 08:49:17,941:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f82253ddd60>
Prep: True
2025-07-06 08:49:17,941:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f82253ddd60> and installer None
2025-07-06 08:49:17,941:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2025-07-06 08:49:17,989:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2510952981', new_authzr_uri=None, terms_of_service=None), 98b1623f627354247b0106fd4fdf86b9, Meta(creation_dt=datetime.datetime(2025, 7, 6, 8, 9, 58, tzinfo=<UTC>), creation_host='e1365ea69981', register_to_eff=None))>
2025-07-06 08:49:17,990:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-07-06 08:49:17,992:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-07-06 08:49:18,140:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 995
2025-07-06 08:49:18,141:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 06 Jul 2025 08:49:18 GMT
Content-Type: application/json
Content-Length: 995
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "DejiD21Hul0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "https://letsencrypt.org/docs/profiles#classic",
      "shortlived": "https://letsencrypt.org/docs/profiles#shortlived (not yet generally available)",
      "tlsserver": "https://letsencrypt.org/docs/profiles#tlsserver"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.5-February-24-2025.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/acme/renewal-info",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-07-06 08:49:18,142:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for apptronium.com and www.apptronium.com
2025-07-06 08:49:18,148:DEBUG:acme.client:Requesting fresh nonce
2025-07-06 08:49:18,148:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-07-06 08:49:18,185:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-07-06 08:49:18,186:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 06 Jul 2025 08:49:18 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: BqzikAvL8fsPU7-Z3sOlL9rrCjYBlT3QjPKUjq5BncEMZYyvjcE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-07-06 08:49:18,186:DEBUG:acme.client:Storing nonce: BqzikAvL8fsPU7-Z3sOlL9rrCjYBlT3QjPKUjq5BncEMZYyvjcE
2025-07-06 08:49:18,187:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "apptronium.com"\n    },\n    {\n      "type": "dns",\n      "value": "www.apptronium.com"\n    }\n  ]\n}'
2025-07-06 08:49:18,191:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjUxMDk1Mjk4MSIsICJub25jZSI6ICJCcXppa0F2TDhmc1BVNy1aM3NPbEw5cnJDallCbFQzUWpQS1VqcTVCbmNFTVpZeXZqY0UiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "mFLAsrSFLWf4BzbuyTgVR2MCplyl3aoY09nOD6NA89d0YOvn9dxGrpjzWAMzwZMa5PU7aPPXMDZLkT2T7hEVuIWDFTDSu8Z5a2VMG4xkT6KTYWGSeJZciMAOe_dFyUIpog4EAiCm3kI_dGp5n5Z4xZMuIVi4BiHU3ndGeRiEr4ifUa00OfiEUU86z81LAM-mtQeDHMIKBGuCZFMtqmG3ISuzcOquRxMiTBcuzL_N50cMvyGJdLK8km9GRRlWNbRRFSZcQKOCGs7kA1a2HNZQYI63B_8A_eDJmFgBI52i-hQFQJvAprLSkSj-YqgH-OIngSGEns0ztRXQnSiYZNz_Cw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImFwcHRyb25pdW0uY29tIgogICAgfSwKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInd3dy5hcHB0cm9uaXVtLmNvbSIKICAgIH0KICBdCn0"
}
2025-07-06 08:49:18,245:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 295
2025-07-06 08:49:18,245:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Sun, 06 Jul 2025 08:49:18 GMT
Content-Type: application/problem+json
Content-Length: 295
Connection: keep-alive
Boulder-Requester: 2510952981
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/docs/rate-limits>;rel="help"
Replay-Nonce: upQSWUsBJz2ixsA9Xaru--gFB2Yu7bNmkElX77I0Blgoj7B8UJI
Retry-After: 535

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "too many failed authorizations (5) for \"apptronium.com\" in the last 1h0m0s, retry after 2025-07-06 08:58:13 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account",
  "status": 429
}
2025-07-06 08:49:18,246:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 478, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 137, in new_order
    response = self._post(self.directory['newOrder'], order)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 365, in _post
    return self.net.post(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 738, in post
    return self._post_once(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 751, in _post_once
    response = self._check_response(response, content_type=content_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 602, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: too many failed authorizations (5) for "apptronium.com" in the last 1h0m0s, retry after 2025-07-06 08:58:13 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account
2025-07-06 08:49:18,250:ERROR:certbot._internal.log:An unexpected error occurred:
2025-07-06 08:49:18,251:ERROR:certbot._internal.log:too many failed authorizations (5) for "apptronium.com" in the last 1h0m0s, retry after 2025-07-06 08:58:13 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account
